---
title: "Data Science & Software"
toc: true
---


::: {.callout-caution collapse="true"}
## TDS IRC and DS&S Collaborative Data Science Consulting
The Translational Data Science Integrated Research Center (TDS IRC) and Data Science & Software teams have partnered together to provide support for data scientists to work with Fred Hutch labs. [Find out how we can help.](https://centernet.fredhutch.org/u/tdsirc/funding/-2024-tds-irc-data-scientist-collaboration.html)
:::





## Translational Data Science and Analytics

Translational Data Science and Analytics is a team of data scientists with the aim of solving [translational problems](https://ascpt.onlinelibrary.wiley.com/doi/10.1111/cts.13055) in data analysis across the Fred Hutch. Our goals are to: 

1. Improve the interoperability, quality, and accessibility of healthcare data, 
2. Develop accelerator data products that address data access and analysis needs while upskilling the data science capabilities at Fred Hutch, and 
3. Understand the user needs around healthcare data at Fred Hutch.


Some examples of what we're working on:

* Implement common data standards such as the [OMOP CDM](https://www.ohdsi.org/data-standardization/)
* Develop user guides and documentation of Fred Hutch’s data assets to improve accessibility and support democratization of data
* Create data products and support [patient data access for research](https://centernet.fredhutch.org/f/data-science-lab/patient-data.html)
* Pilot and prototype self-service tools for working with patient data


### Data Accelerator Products

Data Accelerator Products are versioned, time-bound data science solutions for Fred Hutch clinical researchers. We are interested in developing products that prioritize open source solutions, code sharing within FHCC, reproducibility, and collaborative efforts.

Some examples of this work include:

* Develop data pipelines and 'data-as-a-product' solutions for FHCC patient clinical data access 
* Define rule-based and probabilistic patient cohort defintions
* Interactive visualizations and analysis tools utilizing FHCC clinical data

Our ability to develop top-notch data accelerator products for FHCC team depends on ongoing data infrastructure improvements. We appreciate your patience as we continue to make improvements to the type of solutions that are available for FHCC researchers.

As a data science *lab*, we are interested in learning from the community and testing new ideas. Please reach out to our team with ideas for new data science products.

### Connect with Us

Examples of how our team can work with you:
* Data access and short-term analysis support can be requested on [FHCC CenterNet](https://centernet.fredhutch.org/f/data-science-lab/patient-data.html).
* Provide advice and navigation through a 20 minute [Data House Call](https://calendly.com/data-house-calls)
    + Choose [clinical data access](https://calendly.com/data-house-calls/clinical-data) to meet to Monica (Translational Analytics Manager) and Jenny (Data Governance Specialist) to discuss how we can support you in accessing and using FHCC patient data for research 
    + Choose [data analysis](https://calendly.com/data-house-calls/analysis-viz) to meet with Monica to discuss data analysis and visualization questions
* Consult on research projects through the [TDS IRC](https://centernet.fredhutch.org/u/tdsirc/funding/2023-tds-irc-data-scientist-collaboration.html) funding mechanism
* General questions can be sent to `analytics@fredhutch.org`.



## Research Informatics

Research Informatics supports the use of biomedical datasets in the research context that often include large scale public or private genomic data, licensed or regulated datasets (such as those under DUAs or legal protection like GDPR), or laboratory-generated data that require significant computational processing as part of their analysis.  We focus on providing open-source tooling, best practices for computational workloads and data management, and other resources such as computational workflows and templates that staff can use as a jumping off point to customize for their own work.  We work closely with Fred Hutch IT's Scientific Computing group who provide support for our on-prem computing cluster, scientific data storage, and research applications.  


### Workflow Support in WILDS

We're developing resources in collaboration with the Fred Hutch IT Scientific Computing group to support simplified interfaces to computing resources through our project [PROOF](https://sciwiki.fredhutch.org/dasldemos/proof-how-to/). This will facilitate users running WDL workflows on our cluster and you can find our emerging resources in our WILDS GitHub organization, such as our [WDL supports](https://github.com/orgs/getwilds/repositories?q=cromwell+OR+WDL&type=all&language=&sort=).

### Research Data Applications
We support the private [Fred Hutch instance of cBioPortal](/tools/#cbioportal) in collaboration with Fred Hutch IT's [Scientific Computing group](https://centernet.fredhutch.org/u/it/scicomp.html). cBioPortal allows users to easily explore multidimensional cancer genomics data with an intuitive point-and-click interface. For more information, read the [SciWiki documentation](https://sciwiki.fredhutch.org/dasldemos/fh-cbio-intro/) and visit [cbioportal.fredhutch.org](https://cbioportal.fredhutch.org) to try it out.



### Connect with Us
The DaSL Research Informatics team provides support to the community through documentation on the [Biomedical Data Science Wiki](https://sciwiki.fredhutch.org/), through our new [Community Studios program](/communitystudios/), and through our Data House Calls program.

### Research Data Management House Calls
Use this [Data House Call](https://calendly.com/data-house-calls/management) to discuss questions about research data management, infrastructure, or tools:

- Developing lab or group data management schemes that support research, leverage Fred Hutch infrastructure, and are cost-effective
- Transferring, storing, or collaborating on large datasets
- Accessing data in cloud storages
- Accessing public datasets
- How to work with DUAs, licensed or private datasets
- Learning about and accessing Fred Hutch hosted datasets (e.g., data from our clinics, our large research groups, and reference datasets)
- Managing and accessing reference datasets such as genome data and common bioinformatic tool reference data sets

Or other questions you have that you feel might relate to this topic!  


### Research Computing House Calls

Use this [Data House Call](https://calendly.com/data-house-calls/computing) to discuss questions about how to run your code or analysis more effectively and at scale:

- Using our computing cluster for your analyses
- Writing and running scientific workflows
- Managing and executing WDL workflows via [PROOF](https://sciwiki.fredhutch.org/dasldemos/proof-how-to/)
- Bioinformatics software and environment management (including [Docker](https://github.com/getwilds/wilds-docker-library)!)
- Leveraging Git/GitHub for code management and sharing
- Leveraging cloud-based data storage and/or computing
- Collaboration and sharing of workflows, environments, and large datasets

Or other questions you have that you feel might relate to this topic!  

>Note: Often we pull in folks from the Scientific Computing team to provide expert advice as well so please describe your needs well so we can try to have the right staff ready. 






## Human Computer Interaction



Participate in our Needs Assessment [by scheduling a consultation with Sean](/needs/).

### Our Resources

### Connect with Us

Schedule a discussion on your code or software questions via a [Code and Software, Data House Call type](https://calendly.com/data-house-calls).  