---
title: "Fred Hutch Data Science Lab"
toc: true
sidebar: data-sidebar
---

Fred Hutch’s recent merger to form a hybrid clinical care and research institute brings a diversity of focus, skills, interests and capabilities that can spur innovation. To support this, the Office of the Chief Data Officer works to create a robust and coordinated data ecosystem at Fred Hutch via guiding data infrastructure development with a comprehensive data strategy and integrating technology and philanthropic partnerships to leverage cutting edge innovations to advance our understanding of disease, therapeutics, and patient outcomes.


After the merger of SCCA and FHCRC in April 2022, Fred Hutch Cancer Center is building a secure, scalable, and supportable technical infrastructure foundation and tools that provide a centrally governed, democratized platform. Upon which, the Fred Hutch community can build data products and tooling leveraging multimodal Fred Hutch patient clinical data to support clinical care, operations, clinical trials, precision oncology, data science and AI innovation.  

Clinical and Research Data Solutions (CARDS) will become the foundational infrastructure of the Fred Hutch Cancer Center’s new patient data ecosystem.


As this transformational work continues we will update the [About page](/about.html) to show our data community what they might expect next in terms of new features, support mechanisms and data access.  




::: {.callout-tip appearance="simple"}
If you have questions or ideas about Fred Hutch patient data supports, schedule a [CARDS Data House Call](https://calendly.com/data-house-calls/cards).  
:::

