server {
    listen       80;
    listen  [::]:80;
    server_name  _;

    absolute_redirect off;

    access_log  /var/log/nginx/access.log;
    error_log   /var/log/nginx/error.log warn;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        try_files $uri $uri/ =404;
    }

    location = /proof {
        return 301 /proof/;
    }

    location /proof/ {
        alias /usr/share/nginx/html/proof/;
        index index.html index.htm;
        try_files $uri $uri/ =404;
    }

    error_page 404 /404.html;

    location = /404.html {
        root   /usr/share/nginx/html;
        internal;
    }
}
