---
title: "Translational Applications and Engineering"
toc: true

---

As part of our overall data strategy efforts, we partner with a variety of departments across Fred Hutch to help coordinate and streamline our overall data portfolio.  This work includes aligning our technology resources with data community needs and ensuring connections between subject matter experts in issues such as technology, security and compliance to enable ethical use of data resources at Fred Hutch.  

We also build data infrastructure, applications and data products to support translational use of patient data in a secure, scalable, collaborative way to bridge the gap between the clinic and research.  



::: {.callout-note appearance="minimal"}
All documentation about Data Science Lab Tools and best practices can also be found on the Fred Hutch [Biomedical Data Science Wiki](https://sciwiki.fredhutch.org/).
:::



## Research Applications and Tools

### PROOF
PROOF (PRoduction On-ramp for Optimization and Feasibility) is a user-friendly tool designed for managing and executing WDL (Workflow Description Language) workflows using the Cromwell workflow manager, configured to run on the Fred Hutch cluster. PROOF allows users to:

- **Automate** all the backend Cromwell configurations necessary to run your workflows instantly.
- **Validate**, troubleshoot, assess performance, and run their workflows all under one roof.
- **Refine** their workflows before potential transitions to cloud-based infrastructures, providing a "proofing" resource of sorts.

::: {.callout-note appearance="minimal"}
Find out more on the [PROOF page on the Fred Hutch SciWiki](https://sciwiki.fredhutch.org/datascience/proof/).
:::

### cBioPortal
cBioPortal is an open-source platform for visualization, exploration, and analysis of cancer genomics data sets developed by Memorial Sloan Kettering (MSK). The Data Science Lab (DaSL) in conjunction with the Scientific Computing Group (SciComp) at Fred Hutch have launched a Fred Hutch instance of cBioPortal for research use only. 

The [Fred Hutch deployment of cBioPortal](https://cbioportal.fredhutch.org/) provides users with several advantages to enhance their research:

- The private nature of this instance allows researchers to utilize the powerful visualization tools of the application to facilitate visualization of **internal data**.
- It also provides research groups with the ability to establish **controlled access** to their study data, ensuring data protection.
- Users can host and share their data through the Fred Hutch instance of cBioPortal to **facilitate collaborations**.
- Additionally, this instance and our administration plans have been reviewed and approved by InfoSec to allow users to include individually identifiable research data in their data uploads when investigators have clear IRB approvals in place. 

::: {.callout-note appearance="minimal"}
For more details on what the Fred Hutch instance of cBioPortal can do for you, read our Fred Hutch cBioPortal [product page](https://sciwiki.fredhutch.org/datascience/cbioportal/) and [documentation](https://sciwiki.fredhutch.org/dasldemos/fh-cbio-intro/) on the Fred Hutch SciWiki and visit [cbioportal.fredhutch.org](https://cbioportal.fredhutch.org) to give it a spin.
:::

## Translational Applications and Tools

Fred Hutch is building a secure, scalable, and supportable technical infrastructure foundation and tools that provide a centrally governed, democratized platform. Upon this system, the Fred Hutch community can build data products and tooling leveraging multimodal Fred Hutch patient clinical data to support clinical care, operations, clinical trials, precision oncology, data science and AI innovation.

### CARDS
Clinical and Research Data System (CARDS) will become the foundation of the Fred Hutch Cancer Center’s new translational data ecosystem.

To get up to date information regarding the current state and upcoming availability opportunities please schedule a [Data House Call for Translational Data Needs](https://calendly.com/data-house-calls/cards), or email [oncdataaccess@fredhutch.org](mailto:oncdataaccess@fredhutch.org).  



## Data Product Management & Engineering Teams
Our Data Product Management team partners with various groups on campus and our growing Engineering team to deliver data related products in an responsive and sustainable way. The team supports the management and delivery of responsive and sustainable data-related products. They provide strategic support for data products by managing the data product portfolio, assessing the product landscape in alignment with our strategic goals, and ensuring optimal product development by; streamlining development, coordinating resources, and enhancing visibility across Fred Hutch.


Our work includes:

- Program management of the Fred Hutch Data Initiatives (Strategy & Governance, Patient and Research)
- Product management for our developed Tools and Products
- Product management support for cross-institutional data infrastructure products

Our newly forming Engineering team builds translational data infrastructure and data products to enable new capabilities in translational data science and AI for the Fred Hutch translational data community.  

> More to come on the growing Engineering team over the winter of 2024-2025.  See our [open jobs as well](about.qmd#jobs).

