on:
  workflow_dispatch:
  pull_request:
    branches: [main]
  push:
    branches: [main]

name: Check Quarto Render

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Dependencies
        run: quarto install tinytex

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2

      - name: Render
        uses: quarto-dev/quarto-actions/render@v2
